### ISSUE TITLE
When will the pub.dev package be updated? 

### ISSUE THREAD

**Issue by hansamann** [chirp/chirp-flutter#19]
There was an issue with the Android main ui thread that got fixed, but the flutter pub.dev package is still 0.4.0 - when is the update coming out so I can test the new package?

**Comment by joextodd** [comment]
@hansamann we expect to publish v1.0.0 sometime next week, thanks

**Comment by dinuchiriac** [comment]
Also, @hansamann  please note that this is a public project and anyone can contribute to it.

**Comment by joextodd** [comment]
@hansamann we have published the latest changes to v1.0.0 at https://pub.dev/packages/chirp_flutter.

Please note the plugin has been renamed to `chirp_flutter`. 
The latest version has also changed the way errors are handled, it now uses the recommended flutter mechanism of `try`/`catch` statements. See the [example](https://github.com/chirp/chirp-flutter/tree/master/example)
