### ISSUE TITLE
Unable to run example Code

### ISSUE THREAD

**Issue by harshit77** [chirp/chirp-flutter#2]
HI Joe,

I was trying to run your example code but got the following error.Please help me out 

I installed two packages in pubspec.yaml
simple_permissions: ^0.1.9
chirpsdk: ^0.1.0

Launching lib/main.dart on iPhone XS in debug mode...Running pod install...                                       1.1s
CocoaPods' output:↳
      Preparing
    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
    -> Fetching podspec for `chirpsdk` from `.symlinks/plugins/chirpsdk/ios`
    -> Fetching podspec for `simple_permissions` from `.symlinks/plugins/simple_permissions/ios`

    Resolving dependencies of `Podfile`
    [!] Unable to find a specification for `ChirpSDK` depended upon by `chirpsdk`

    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:402:in `find_cached_set'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in
    `specifications_for_dependency'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in
    sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:53
    :in `block in sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:70
    :in `with_no_such_dependency_error_handling'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/delegates/specification_provider.rb:52
    :in `sort_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:754:in
    `push_state_for_requirements'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:746:in
    `require_nested_dependencies_for'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:729:in
    `activate_new_spec'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:686:in
    `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:254:in
    `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/molinillo-0.6.5/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in
    `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in
    `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
    /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] `<PBXGroup UUID=`97C146E51CF9000F007C117D`>` attempted to initialize an object with an unknown UUID.
    `CF3B75C9A7D2FA2A4C99F110` for attribute: `children`. This can be the result of a merge and  the unknown UUID is
    being discarded.

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified.
    Please specify a platform for this target in your Podfile. See
    `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install
Error launching application on iPhone XS.

**Comment by joextodd** [comment]
Could you confirm which version of cocoapods you are using with `pod --version`?

**Comment by joextodd** [comment]
Does [this](https://github.com/flutter/flutter/issues/11000) resolve the issue?

**Comment by harshit77** [comment]
Pod version is 1.5.3
No it is still throwing me the same error.

**Comment by harshit77** [comment]
@joextodd  Any Update ?

**Comment by joextodd** [comment]
The Podfile issue there is just a warning, however you should be able to get rid of this by opening `example/ios/Podfile` and uncommenting the line at the top that says 

`# Uncomment this line to define a global platform for your project`
`platform :ios, '10.0'`
`use_frameworks!`

The PBXGroup issue, I have not seen before, and cannot replicate on my end...

**Comment by joextodd** [comment]
Could you change directory to the example folder and run `flutter build ios` and paste the output please?

**Comment by harshit77** [comment]
All other flutter projects are working fine.I guess there is some PBXgroup issue.Even uncomment the platform part couldn't help me

Here is the output of **flutter build ios**
════════════════════════════════════════════════════════════════════════════════
No valid code signing certificates were found
You can connect to your Apple Developer account by signing in with your Apple ID
in Xcode and create an iOS Development Certificate as well as a Provisioning
Profile for your project by:
  1- Open the Flutter project's Xcode target with
       open ios/Runner.xcworkspace
  2- Select the 'Runner' project in the navigator then the 'Runner' target
     in the project settings
  3- In the 'General' tab, make sure a 'Development Team' is selected.
     You may need to:
         - Log in with your Apple ID in Xcode first
         - Ensure you have a valid unique Bundle ID
         - Register your device with your Apple Developer Account
         - Let Xcode automatically provision a profile for your app
  4- Build or run your project again
  5- Trust your newly created Development Certificate on your iOS device
     via Settings > General > Device Management > [your new certificate] > Trust

For more information, please visit:
  https://developer.apple.com/library/content/documentation/IDEs/Conceptual/
  AppDistributionGuide/MaintainingCertificates/MaintainingCertificates.html

Or run on an iOS simulator without code signing
════════════════════════════════════════════════════════════════════════════════
No development certificates available to code sign app for device deployment

**Comment by joextodd** [comment]
Have you gone through these steps to enable your provisioning profile?

**Comment by harshit77** [comment]
No @joextodd.

**Comment by joextodd** [comment]
Could you try run through those and report back if it does/doesn't solve the problem 👍

**Comment by agreensh** [comment]
You need to run 'pod update' before running 'pod install' to update your pod repository, otherwise it will not find the ChirpSDK.

**Comment by harshit77** [comment]
HI @joextodd ,

Sry for the late reply.
Sharing you the output after I ran "**flutter run**".
Launching lib/main.dart on iPhone XS in debug mode...
Running pod install...                                       1.5s
Starting Xcode build...
Xcode build done.                                            6.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET chirpsdk OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/hsahu/Desktop/Development/flutter/.pub-cache/hosted/pub.dartlang.org/simple_permissions-0.1.9/ios/Classes/Si
    mplePermissionsPlugin.m:2:9: fatal error: 'simple_permissions/simple_permissions-Swift.h' file not found
    #import <simple_permissions/simple_permissions-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by harshit77** [comment]
HI @joextodd ,

Finally I can see the example code.Here is what we needs to do

When the iOS part of a plugin is coded using Swift, you must make that change to your **ios/Podfile**. You must add **use_frameworks!** after **platform :ios, '10.0'**

**Comment by joextodd** [comment]
Thanks @harshit77 for the update, I will close this issue if everything is running ok now
