### ISSUE TITLE
iOS crashes if invalid payload received 

### ISSUE THREAD

**Issue by shankar-dandapat** [chirp/chirp-flutter#22]
Affecting both my code and the Chirp Flutter example.

If an audio payload is only partially played or somehow the payload becomes fragmented during playback, an iOS device using the Flutter Chirp SDK will crash resulting in the following error: 

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Data cannot be nil'

The same scenario with the same Chirp Flutter SDK does not happen when running the Flutter code on Android.  

Recently, the ability to catch errors (ChirpSDK.onError()) has been deprecated and I believed the onError() Flutter function was able to catch such "Data cannot be nil" exceptions.

What are possible resolutions to ensure an iOS app won't completely crash when an invalid payload is received?

Flutter version: Flutter (Channel stable, v1.9.1+hotfix.6
ChirpSDK: Latest version from 10/23/19 commit

**Comment by karthikmuralidharan** [comment]
I too am experiencing the same issue on iOS with the Chirp Flutter SDK.

**Comment by joextodd** [comment]
Thanks for reporting this. See the fix in #25
