### ISSUE TITLE
Not working on my Galaxy note 9 - Fatal Error

### ISSUE THREAD

**Issue by iampawan** [chirp/chirp-flutter#3]
It's working fine in emulator but getting a fatal error with note 9. I tried to figure it out why but couldn't

**Comment by joextodd** [comment]
Could you post any error messages from the log?

**Comment by iampawan** [comment]
Yes I can

**Comment by iampawan** [comment]
--no-link-platform --incremental --packages /Users/pawankumar/Desktop/dart/mobile/flutterchirp/.packages --output-dill
build/app.dill --depfile
/Users/pawankumar/Desktop/dart/mobile/flutterchirp/build/app/intermediates/flutter/debug/snapshot_blob.bin.d --filesystem-scheme
org-dartlang-root package:flutterchirp/main.dart
[ +994 ms] [+1289 ms] Unhandled exception:
[   +5 ms]            NoSuchMethodError: The getter 'asLibrary' was called on null.
[        ]            Receiver: null
[        ]            Tried calling: asLibrary
[        ]            #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
[        ]            #1      LibraryDependency.targetLibrary (package:kernel/ast.dart:501:57)
[        ]            #2      BuilderGraph.neighborsOf (package:front_end/src/fasta/builder_graph.dart:55:30)
[        ]            #3      _SyncIterator.moveNext (dart:core/runtime/libcore_patch.dart:151:12)
[        ]            #4      IncrementalCompiler.computeReusedLibraries
(package:front_end/src/fasta/incremental_compiler.dart:636:34)
[        ]            #5      IncrementalCompiler.computeDelta.<anonymous closure>
(package:front_end/src/fasta/incremental_compiler.dart:200:46)
[   +2 ms]            <asynchronous suspension>
[        ]            #6      CompilerContext.runInContext.<anonymous closure>.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:120:46)
[        ]            #7      new Future.sync (dart:async/future.dart:224:31)
[        ]            #8      CompilerContext.runInContext.<anonymous closure>
(package:front_end/src/fasta/compiler_context.dart:120:19)
[        ]            #9      _rootRun (dart:async/zone.dart:1124:13)
[        ]            #10     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ]            #11     _runZoned (dart:async/zone.dart:1516:10)
[        ]            #12     runZoned (dart:async/zone.dart:1463:12)
[        ]            #13     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:119:12)
[        ]            #14     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:107:20)
[        ]            <asynchronous suspension>
[        ]            #15     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:50:44)
[        ]            <asynchronous suspension>
[        ]            #16     FrontendCompiler.compile.<anonymous closure> (package:vm/frontend_server.dart:332:67)
[        ]            #17     new Future.<anonymous closure> (dart:async/future.dart:176:37)
[        ]            #18     _rootRun (dart:async/zone.dart:1120:38)
[        ]            #19     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ]            #20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
[        ]            #21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
[        ]            #22     _rootRun (dart:async/zone.dart:1124:13)
[        ]            #23     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ]            #24     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
[        ]            #25     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
[        ]            #26     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
[        ]            #27     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
[        ]            #28     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[  +85 ms] [  +98 ms] "flutter bundle" took 2,138ms.
[        ] Compiler failed on /Users/pawankumar/Desktop/dart/mobile/flutterchirp/lib/main.dart
[        ] #0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
[        ] #1      build (package:flutter_tools/src/bundle.dart:117:7)
[        ] <asynchronous suspension>
[        ] #2      BuildBundleCommand.runCommand (package:flutter_tools/src/commands/build_bundle.dart:86:11)
[        ] <asynchronous suspension>
[        ] #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:18)
[        ] <asynchronous suspension>
[        ] #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:472:33)
[        ] <asynchronous suspension>
[        ] #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
[        ] <asynchronous suspension>
[        ] #6      _rootRun (dart:async/zone.dart:1124:13)
[        ] #7      _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #8      _runZoned (dart:async/zone.dart:1516:10)
[        ] #9      runZoned (dart:async/zone.dart:1463:12)
[        ] #10     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
[        ] <asynchronous suspension>
[        ] #11     FlutterCommand.run (package:flutter_tools/src/runner/flutter_command.dart:463:20)
[        ] #12     CommandRunner.runCommand (package:args/command_runner.dart:196:27)
[        ] <asynchronous suspension>
[        ] #13     FlutterCommandRunner.runCommand.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command_runner.dart:401:21)
[        ] <asynchronous suspension>
[        ] #14     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
[        ] <asynchronous suspension>
[        ] #15     _rootRun (dart:async/zone.dart:1124:13)
[        ] #16     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #17     _runZoned (dart:async/zone.dart:1516:10)
[        ] #18     runZoned (dart:async/zone.dart:1463:12)
[        ] #19     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
[        ] <asynchronous suspension>
[        ] #20     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:361:19)
[        ] <asynchronous suspension>
[        ] #21     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:111:29)
[        ] #22     new Future.sync (dart:async/future.dart:224:31)
[        ] #23     CommandRunner.run (package:args/command_runner.dart:111:11)
[        ] #24     FlutterCommandRunner.run (package:flutter_tools/src/runner/flutter_command_runner.dart:241:18)
[        ] #25     run.<anonymous closure> (package:flutter_tools/runner.dart:60:20)
[        ] <asynchronous suspension>
[        ] #26     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:142:29)
[        ] <asynchronous suspension>
[        ] #27     _rootRun (dart:async/zone.dart:1124:13)
[        ] #28     _CustomZone.run (dart:async/zone.dart:1021:19)
[        ] #29     _runZoned (dart:async/zone.dart:1516:10)
[        ] #30     runZoned (dart:async/zone.dart:1463:12)
[        ] #31     AppContext.run (package:flutter_tools/src/base/context.dart:141:18)
[        ] <asynchronous suspension>
[        ] #32     runInContext (package:flutter_tools/src/context_runner.dart:44:24)
[        ] <asynchronous suspension>
[        ] #33     run (package:flutter_tools/runner.dart:51:10)
[        ] #34     main (package:flutter_tools/executable.dart:51:9)
[        ] <asynchronous suspension>
[        ] #35     main (file:///Users/pawankumar/Desktop/flutter/flutter/packages/flutter_tools/bin/flutter_tools.dart:8:3)
[        ] #36     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:287:32)
[        ] #37     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
[        ] > Task :app:flutterBuildDebug FAILED
[        ] 13 actionable tasks: 1 executed, 12 up-to-date
[ +436 ms] Gradle task 'assembleDebug'... (completed)
[  +12 ms] "flutter run" took 18,970ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:26:3)
#1      _buildGradleProjectV2 (package:flutter_tools/src/android/gradle.dart:418:5)
<asynchronous suspension>
#2      buildGradleProject (package:flutter_tools/src/android/gradle.dart:310:14)
<asynchronous suspension>
#3      buildApk (package:flutter_tools/src/android/apk.dart:43:10)
<asynchronous suspension>
#4      AndroidDevice.startApp (package:flutter_tools/src/android/android_device.dart:379:13)
<asynchronous suspension>
#5      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:292:54)
<asynchronous suspension>
#6      HotRunner.run (package:flutter_tools/src/run_hot.dart:275:39)
<asynchronous suspension>
#7      RunCommand.runCommand (package:flutter_tools/src/commands/run.dart:378:37)
<asynchronous suspension>
#8      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:538:18)
#9      _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#10     _rootRunUnary (dart:async/zone.dart:1132:38)
#11     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#12     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#13     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#14     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#15     Future._complete (dart:async/future_impl.dart:473:7)
#16     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#17     _AsyncAwaitCompleter.complete (dart:async/runtime/libasync_patch.dart:28:18)
#18     _completeOnAsyncReturn (dart:async/runtime/libasync_patch.dart:294:13)
#19     RunCommand.usageValues (package:flutter_tools/src/commands/run.dart)
#20     _asyncThenWrapperHelper.<anonymous closure> (dart:async/runtime/libasync_patch.dart:77:64)
#21     _rootRunUnary (dart:async/zone.dart:1132:38)
#22     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#23     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#24     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#25     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#26     Future._complete (dart:async/future_impl.dart:473:7)
#27     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#28     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async/runtime/libasync_patch.dart:33:20)
#29     _rootRun (dart:async/zone.dart:1124:13)
#30     _CustomZone.run (dart:async/zone.dart:1021:19)
#31     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
#32     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#34     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#35     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)

**Comment by iampawan** [comment]
@joextodd Let me know if you need any other info.

**Comment by harshit77** [comment]
hi @iampawan ,

Did you face any issue in running the example code in iOS because i logged an issue here [https://github.com/chirp/chirp-connect-flutter/issues/2](url)  .If not could you please create a video for it.
Thanks for creating lot of videos on flutter I learned a lot from your youtube videos

**Comment by joextodd** [comment]
@iampawan this could potentially be related to https://github.com/chirp/chirp-android-examples/issues/5#issuecomment-466366873

will keep this thread posted on any updates

**Comment by iampawan** [comment]
In that case @joextodd how does it work on Shuttl? Are they using different sdk?
