### ISSUE TITLE
META-INF/chirpsdk_release.kotlin_module

### ISSUE THREAD

**Issue by BeaumerF** [chirp/chirp-flutter#4]
Hello,

I wanted to build your example project because running debug apk works, but not the release building :

> ./ >flutter build apk
> Running "flutter packages get" in example...                 5,6s
> Initializing gradle...                                       1,3s
> Resolving dependencies...                                   21,3s
> Gradle task 'assembleRelease'...
> Calling mockable JAR artifact transform to create file: C:\Users\X\.gradle\caches\transforms-1\files-1.1\android.jar\dd7ac0215c51c4c77c4f101a0b35b7aa\android.jar with input C:\Users\X\AppData\Local\Android\sdk\platforms\android-27\android.jar
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:transformResourcesWithMergeJavaResForRelease'.
> > More than one file was found with OS independent path 'META-INF/chirpsdk_release.kotlin_module'
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2m 18s
> Gradle task 'assembleRelease'... Done                       140,1s
> Gradle task assembleRelease failed with exit code 1

Do you know how can I fix this ?

Thank you in advance.

**Comment by joextodd** [comment]
Can you try adding this to the app's build.gradle file.

```
android {
    packagingOptions {
         exclude 'META-INF/chirpsdk_release.kotlin_module'
    }
}
```
