### ISSUE TITLE
More than one file was found with OS independent path 'META-INF/chirpsdk_release.kotlin_module'

### ISSUE THREAD

**Issue by bhu1oja** [chirp/chirp-flutter#7]
FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':app:transformResourcesWithMergeJavaResForRelease'.
More than one file was found with OS independent path 'META-INF/chirpsdk_release.kotlin_module'

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org

BUILD FAILED in 7s
Running Gradle task 'assembleRelease'...
Running Gradle task 'assembleRelease'... Done 8.7s
Gradle task assembleRelease failed with exit code 1
**exclude 'META-INFchirpsdk_release.kotlin_module DOESNOT WORK, app CRASH after including this code** 
**It perfectly works on debug app **

**Comment by joextodd** [comment]
Hi @bhu1oja, can you confirm that you added this to your app's `build.gradle`?

```
android {      
    packagingOptions {
        exclude 'META-INF/chirpsdk_release.kotlin_module'
    }
}
```

This solution worked for this user - https://github.com/chirp/chirp-flutter/issues/4
