### ISSUE TITLE
ChirpSDK.init never ends

### ISSUE THREAD

**Issue by lewixlabs** [chirp/chirp-flutter#8]
Hi,
as the subject of this issue, from Android app, calling
`await ChirpSDK.init`
(in async method of course)
code never goes ahead at the next method.
In stack trace no exception I found.

I inserted, as described:
- check permissions with same plugin you mentioned
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="dev.llabs.test_soundpay">
    <!-- Flutter needs it to communicate with the running application
         to allow setting breakpoints, to provide hot reload, etc.
    -->
        <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
</manifest>

```

 ```
 Future<bool> _requestPermissions() async {
    bool permission = await SimplePermissions.checkPermission(Permission.RecordAudio);
    if (!permission) {
      var permissionResult = await SimplePermissions.requestPermission(Permission.RecordAudio);
      return permissionResult == PermissionStatus.authorized;
    }

    return permission;
  }

  _initChirp() async {
    var okPermissions = await _requestPermissions();
    if (!okPermissions)
      return;
    await ChirpSDK.init(_appKey, _appSecret);
    await ChirpSDK.setConfig(_appConfig);
    await ChirpSDK.start();
  }

  @override
  void initState() {
    super.initState();
    _initChirp();
  }
```
- license strings related to my chirp account.

Using your demo app, chirp sdk works (after Chirp.init Chirp.setConfig is reached and called).
What am I missing?
My first suspect was using java as sub andrdroid project, instead kotlin, but nothing changed
Thank you for any suggestions

**Comment by joextodd** [comment]
Have you tried using the `onError` callback to see if there are any error messages sent back from the ChirpSDK?

```dart
ChirpSDK.onError.listen((e) {
  setState(() {
    _chirpErrors = e.message;
  });
});
```

**Comment by lewixlabs** [comment]
> Have you tried using the `onError` callback to see if there are any error messages sent back from the ChirpSDK?
> 
> ```dart
> ChirpSDK.onError.listen((e) {
>   setState(() {
>     _chirpErrors = e.message;
>   });
> });
> ```

Nope..., callback is never reached.

**UPDATE**
Found the issue!
I'm not expert about dart language, but this is very weird:
```

  Future<void> _initChirp() async {
    await ChirpSDK.init(_appKey, _appSecret);
  }

  Future<void> _configureChirp() async {
    await ChirpSDK.setConfig(_appConfig);
  }

  _initApp() async {

    // WORKS! Second method is reached
    _initChirp();
    _configureChirp();

    // DOESNT WORK! Second method is never reached
    // await ChirpSDK.init(_appKey, _appSecret);
    // await ChirpSDK.setConfig(_appConfig);
  }
```
Chirp SDK async methods must called inside a Future<void> async parent method.
Sorry if this is a newbie mistake

**Comment by joextodd** [comment]
Ah yes, I did spot that when developing - not a Dart expert either, please report back if you figure out the differences 👍

**Comment by lewixlabs** [comment]
Ok also main project works!
Maybe you should update your pub page to suggest using Future<void> parent method
https://pub.dartlang.org/packages/chirpsdk

Thank you again.
Hi!
Lewix
